// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApdfezXc7BkjE-x5HTeDcjKvNHGy4XVN0',
    appId: '1:221445753309:web:aaccca4499330416c58e34',
    messagingSenderId: '221445753309',
    projectId: 'my-flutter-app-8bc65',
    authDomain: 'my-flutter-app-8bc65.firebaseapp.com',
    storageBucket: 'my-flutter-app-8bc65.firebasestorage.app',
    measurementId: 'G-6N73MKGC6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM8gN6zxP_KsXENALLaR4kYNW6Oe2mFs4',
    appId: '1:221445753309:android:24627f020a62c210c58e34',
    messagingSenderId: '221445753309',
    projectId: 'my-flutter-app-8bc65',
    storageBucket: 'my-flutter-app-8bc65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASvUIYkb4jrAO7FjsCN50SMX0mK5ujX-M',
    appId: '1:221445753309:ios:47e09a1a6cdd6747c58e34',
    messagingSenderId: '221445753309',
    projectId: 'my-flutter-app-8bc65',
    storageBucket: 'my-flutter-app-8bc65.firebasestorage.app',
    iosBundleId: 'com.example.pharmaGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASvUIYkb4jrAO7FjsCN50SMX0mK5ujX-M',
    appId: '1:221445753309:ios:47e09a1a6cdd6747c58e34',
    messagingSenderId: '221445753309',
    projectId: 'my-flutter-app-8bc65',
    storageBucket: 'my-flutter-app-8bc65.firebasestorage.app',
    iosBundleId: 'com.example.pharmaGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApdfezXc7BkjE-x5HTeDcjKvNHGy4XVN0',
    appId: '1:221445753309:web:fa0a89d9c775cdc0c58e34',
    messagingSenderId: '221445753309',
    projectId: 'my-flutter-app-8bc65',
    authDomain: 'my-flutter-app-8bc65.firebaseapp.com',
    storageBucket: 'my-flutter-app-8bc65.firebasestorage.app',
    measurementId: 'G-56TWH9LYVE',
  );
}
